// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_J107r1ihrZdba2_z2rh3q_x-_UnFQXI',
    appId: '1:467685361541:web:5d1ecddc0b96edab06a6ec',
    messagingSenderId: '467685361541',
    projectId: 'khet-app-2025',
    authDomain: 'khet-app-2025.firebaseapp.com',
    storageBucket: 'khet-app-2025.firebasestorage.app',
    measurementId: 'G-MZKBH79018',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDivmLl0hPtqx0D3qUpfc5HLf7FNJ-07fU',
    appId: '1:467685361541:android:ffc3fdab80c2b44006a6ec',
    messagingSenderId: '467685361541',
    projectId: 'khet-app-2025',
    storageBucket: 'khet-app-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClH8XGgtQklH8d5V7SzPJoBsW7UvVQCT0',
    appId: '1:467685361541:ios:cad29b2e6788c41906a6ec',
    messagingSenderId: '467685361541',
    projectId: 'khet-app-2025',
    storageBucket: 'khet-app-2025.firebasestorage.app',
    androidClientId: '467685361541-1ea8steq31umv0ukp7mtufd0bqdj8mlf.apps.googleusercontent.com',
    iosBundleId: 'com.todo.todo',
  );
}
